### ISSUE TITLE
[QUESTION] How to limit cache to 1Mb

### ISSUE THREAD

**Issue by jhdscript** [Rambalac/ACDDokanNet#22]
Hello,

I'm trying to use ACDDokanNet (which is a very great Dokan Mod) to upload large file to ACD using supercopier.

The problem is the file is marked a uploaded but in real all the file has been cached. 

Is it possible to reduce really (like 1Mb max) the cache to direct writing the file ?

**Comment by Rambalac** [comment]
No, "small file" size is only for download. Upload is more complicated, there is no way to write directly as windows writes by blocks and Amazon allow upload only whole file, so I have to wait till whole file is cached on disk and then upload it.

**Comment by jhdscript** [comment]
But how works acd upload ? junk files ?

**Comment by Rambalac** [comment]
When file is opened for CreateNew it's creating new file in upload cache and passing all write and read operations to it. When file get closed it get added to upload queue. But I believe I should add some delay between closing and adding to queue, because some applications try to open file for write multiple times
